services:
  server:
    image: hf2ollama-${USER}:server
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./models:/models
    ulimits:
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
